app/controllers/c_beasiswa_utk.py
from operator import and_
from flask import Blueprint, jsonify, redirect, render_template, request, url_for
from sqlalchemy import null
from app.models.ukt_model import UktModel
from app.models.user_model import UserModel as User
from app.models.fakultas_model import FakultasModel as Fakultas
from app.models.jurusan_model import JurusanModel as Jurusan
from app.models.semester_model import SemesterModel as Semester
from app.lib.helper import listRealtionUser as RelasiUser, listRelationFakultas as RelasiFakultas, \
    listRelationJurusan as RelasiJurusan, listRelationSemester as RelasiSms
from app.extensions import db
from app.lib.get_count_ukt import bFakultas, bJurusan, totalData, totalTerima, totalTidak

ukt = Blueprint('ukt', __name__, template_folder='../templates/pages/ukt')


@ukt.route('/ukt', methods=['GET'])
def indexUkt():
    # query = UktModel.query.join(User, Fakultas, Jurusan, Semester).all()
    query = db.session.query(UktModel, User, Fakultas, Jurusan, Semester).join(
        User, Fakultas, Jurusan, Semester).all()

    # pc1 = 0
    # pcTotal = 0

    # if query:
    #     pcTotal = totalData()
    #     pc1 = totalTerima()
    #     return pcTotal, pc1
    # pc0 = totalTidak()
    # pf1 = bFakultas(1)
    # pj = bJurusan(1)

    # return render_template('ukt-page.html', query=query, pcTotal=pcTotal, pc0=pc0, pc1=pc1, pf1=pf1, pj=pj)
    return render_template('ukt-page.html', query=query)


@ ukt.route('/add-ukt', methods=['GET', 'POST'])
def addUkt():
    if request.method == 'GET':
        user = RelasiUser(User)
        fakultas = RelasiFakultas(Fakultas)
        jurusan = RelasiJurusan(Jurusan)
        semester = RelasiSms(Semester)
        return render_template('ukt-add.html', user=user, fakultas=fakultas,
                               jurusan=jurusan, semester=semester)
    else:
        nama = request.form.get('nama')
        fakultas = request.form.get('fakultas')
        jurusan = request.form.get('jurusan')
        semester = request.form.get('semester')
        ipk = request.form.get('ipk')
        status_mhs = request.form.get('status')
        organisasi_mhs = request.form.get('organisasi')
        jml_tanggungan = request.form.get('tanggungan')
        jml_pendapatan = request.form.get('pendapatan')
        bantuan = request.form.get('bantuan')

        save = UktModel(user_id=nama, fakultas_id=fakultas, jurusan_id=jurusan, semester_id=semester,
                        ipk=ipk, status_mhs=status_mhs, organisasi_mhs=organisasi_mhs,
                        jml_tanggungan=jml_tanggungan, jml_pendapatan=jml_pendapatan,
                        bantuan=bantuan)
        db.session.add(save)
        db.session.commit()
        return redirect(url_for('ukt.indexUkt'))


@ukt.route('/ukt-testing')
def testUkt():
    if request.method == 'GET':
        user = RelasiUser(User)
        fakultas = RelasiFakultas(Fakultas)
        jurusan = RelasiJurusan(Jurusan)
        semester = RelasiSms(Semester)
        return render_template('ukt-test-page.html', user=user, fakultas=fakultas,
                               jurusan=jurusan, semester=semester)


@ukt.route('/jurusan/<id>')
def arrayJurusan(id):
    # array = Jurusan.query.join(Fakultas).all()
    array = db.session.query(Jurusan, Fakultas).join(
        Fakultas).filter_by(id=id).all()

    data = []
    for i, x in array:
        obj = {}
        obj['id'] = i.id
        obj['jurusan'] = i.jurusan
        obj['id_fakultas'] = x.fakultas
        data.append(obj)

    # jurusan = RelasiJurusan(Jurusan)

    return jsonify({'fakultas_id': data})

app/controllers/c_dashboard.py
from flask import Blueprint, render_template

dashboard = Blueprint('dashboard', __name__,
                      template_folder='../templates/pages')


@dashboard.route('/')
def indexDashboard():
    return render_template('dashboard.html')

app/templates/layouts/header.html
<div class="header">
  <div class="header-left">
    <a href="#" class="logo">
      <img src="../static/img/logo.png" alt="logo" />
      TEKNIK UIM
    </a>
  </div>

  <a href="javasript:void(0)" id="toggle_btn">
    <i class="fe fe-text-align-left"></i>
  </a>

  <div class="top-nav-search">
    <form>
      <input type="text" class="form-control" placeholder="Search here" />
      <button class="btn" type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>

  <a href="mobile_btn" id="mobile_btn">
    <i class="fa fa-bar"></i>
  </a>

  <!-- header menu -->
  <ul class="nav user-menu">
    <!-- notification -->
    {#
    <li class="nav-item dropdown noti-dropdown">
      <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown"> <i class="fa fa-bell"></i> <span class="badge badge-pill"> 3 </span> </a>
      <div class="dropdown-menu notifications">
        <div class="topnav-dropdown-header">
          <span class="notification-title">Notifications</span>
          <a href="javascript:void(0)" class="clear-noti"> Clear All </a>
        </div>

        <div class="noti-content">
          <ul class="notification-list">
            <li class="notification-message">
              <a href="#">
                <div class="media d-flex">
                  <span class="avatar avatar-sm flex-shrink-0">
                    <img class="avatar-img rounded-circle" alt="User Image" src="assets/img/profiles/avatar-02.jpg" />
                  </span>
                  <div class="media-body flex-grow-1">
                    <p class="noti-details"><span class="noti-title">Carlson Tech</span> has approved <span class="noti-title">your estimate</span></p>
                    <p class="noti-time"><span class="notification-time">4 mins ago</span></p>
                  </div>
                </div>
              </a>
            </li>
            <li class="notification-message">
              <a href="#">
                <div class="media d-flex">
                  <span class="avatar avatar-sm flex-shrink-0">
                    <img class="avatar-img rounded-circle" alt="User Image" src="assets/img/profiles/avatar-11.jpg" />
                  </span>
                  <div class="media-body flex-grow-1">
                    <p class="noti-details"><span class="noti-title">International Software Inc</span> has sent you a invoice in the amount of <span class="noti-title">$218</span></p>
                    <p class="noti-time"><span class="notification-time">6 mins ago</span></p>
                  </div>
                </div>
              </a>
            </li>
            <li class="notification-message">
              <a href="#">
                <div class="media d-flex">
                  <span class="avatar avatar-sm flex-shrink-0">
                    <img class="avatar-img rounded-circle" alt="User Image" src="assets/img/profiles/avatar-17.jpg" />
                  </span>
                  <div class="media-body flex-grow-1">
                    <p class="noti-details"><span class="noti-title">John Hendry</span> sent a cancellation request <span class="noti-title">Apple iPhone XR</span></p>
                    <p class="noti-time"><span class="notification-time">8 mins ago</span></p>
                  </div>
                </div>
              </a>
            </li>
            <li class="notification-message">
              <a href="#">
                <div class="media d-flex">
                  <span class="avatar avatar-sm flex-shrink-0">
                    <img class="avatar-img rounded-circle" alt="User Image" src="assets/img/profiles/avatar-13.jpg" />
                  </span>
                  <div class="media-body flex-grow-1">
                    <p class="noti-details"><span class="noti-title">Mercury Software Inc</span> added a new product <span class="noti-title">Apple MacBook Pro</span></p>
                    <p class="noti-time"><span class="notification-time">12 mins ago</span></p>
                  </div>
                </div>
              </a>
            </li>
          </ul>
        </div>
        <div class="topnav-dropdown-footer">
          <a href="#">View all Notifications</a>
        </div>
      </div>
    </li>
    #}
    <!--- end notification --->

    <!--- Profil --->
    <li class="nav-item dropdown has-arrow">
      <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
        <span class="user-img"><img class="rounded-circle" src="../static/img/profiles/avatar-01.jpg" width="31" alt="Seema Sisty" /></span>
      </a>
      <div class="dropdown-menu">
        <div class="user-header">
          <div class="avatar avatar-sm">
            <img src="../static/img/profiles/avatar-01.jpg" alt="User Image" class="avatar-img rounded-circle" />
          </div>
          <div class="user-text">
            <h6>Seema Sisty</h6>
            <p class="text-muted mb-0">Administrator</p>
          </div>
        </div>
        <a class="dropdown-item" href="general.html">My Profile</a>
        <a class="dropdown-item" href="general.html">Account Settings</a>
        <a class="dropdown-item" href="login.html">Logout</a>
      </div>
    </li>
    <!-- end profil -->
  </ul>
</div>

app/templates/layouts/sidebar.html
<div class="sidebar-inner slimscroll">
  <div id="sidebar-menu" class="sidebar-menu">
    <ul>
      <li class="menu-title"></li>
      <li class="{{'active' if filename == 'dashboard' else ''}}">
        <a href=" {{url_for('dashboard.indexDashboard')}} "><i class="fe fe-home"></i> <span>Dashboard</span></a>
      </li>
      <li class="submenu">
        <a href="#"><i class="fe fe-table"></i> <span>Training Data</span> <span class="menu-arrow"></span></a>
        <ul style="display: none">
          <li><a href=" {{url_for('ukt.indexUkt')}} " class="{{'active' if filename == 'indexUkt' or filename == 'addUkt' else ''}}">Beasiswa UKT</a></li>
          <li><a href="#" class="">Beasiswa PPA</a></li>
          <li><a href="#" class="">Beasiswa Bidik Misi</a></li>
        </ul>
      </li>
      <li class="submenu">
        <a href="#"><i class="fe fe-table"></i> <span>Testing Data</span> <span class="menu-arrow"></span></a>
        <ul style="display: none">
          <li><a href=" {{url_for('ukt.testUkt')}} " class="{{'active' if filename == 'testUkt'  else ''}}">Beasiswa UKT</a></li>
          <li><a href="#" class="">Beasiswa PPA</a></li>
          <li><a href="#" class="">Beasiswa Bidik Misi</a></li>
        </ul>
      </li>
      <li class="{{'active' if filename == 'indexUser' or filename == 'addUser' else ''}}">
        <a href=" {{url_for('users.indexUser')}} "><i class="fe fe-user"></i> <span>Data User</span></a>
      </li>
    </ul>
  </div>
</div>