app/controllers/c_beasiswa_utk.py
from operator import and_
from flask import Blueprint, jsonify, redirect, render_template, request, url_for
from sqlalchemy import null
from app.models.ukt_model import UktModel
from app.models.user_model import UserModel as User
from app.models.fakultas_model import FakultasModel as Fakultas
from app.models.jurusan_model import JurusanModel as Jurusan
from app.models.semester_model import SemesterModel as Semester
from app.lib.helper import listRealtionUser as RelasiUser, listRelationFakultas as RelasiFakultas, \
    listRelationJurusan as RelasiJurusan, listRelationSemester as RelasiSms
from app.extensions import db
from app.lib.get_count_ukt import bFakultas, bJurusan, totalData, totalTerima, totalTidak

ukt = Blueprint('ukt', __name__, template_folder='../templates/pages/ukt')


@ukt.route('/ukt', methods=['GET'])
def indexUkt():
    # query = UktModel.query.join(User, Fakultas, Jurusan, Semester).all()
    query = db.session.query(UktModel, User, Fakultas, Jurusan, Semester).join(
        User, Fakultas, Jurusan, Semester).all()

    # pc1 = 0
    # pcTotal = 0

    # if query:
    #     pcTotal = totalData()
    #     pc1 = totalTerima()
    #     return pcTotal, pc1
    # pc0 = totalTidak()
    # pf1 = bFakultas(1)
    # pj = bJurusan(1)

    # return render_template('ukt-page.html', query=query, pcTotal=pcTotal, pc0=pc0, pc1=pc1, pf1=pf1, pj=pj)
    return render_template('ukt-page.html', query=query)


@ ukt.route('/add-ukt', methods=['GET', 'POST'])
def addUkt():
    if request.method == 'GET':
        user = RelasiUser(User)
        fakultas = RelasiFakultas(Fakultas)
        jurusan = RelasiJurusan(Jurusan)
        semester = RelasiSms(Semester)
        return render_template('ukt-add.html', user=user, fakultas=fakultas,
                               jurusan=jurusan, semester=semester)
    else:
        nama = request.form.get('nama')
        fakultas = request.form.get('fakultas')
        jurusan = request.form.get('jurusan')
        semester = request.form.get('semester')
        ipk = request.form.get('ipk')
        status_mhs = request.form.get('status')
        organisasi_mhs = request.form.get('organisasi')
        jml_tanggungan = request.form.get('tanggungan')
        jml_pendapatan = request.form.get('pendapatan')
        bantuan = request.form.get('bantuan')

        save = UktModel(user_id=nama, fakultas_id=fakultas, jurusan_id=jurusan, semester_id=semester,
                        ipk=ipk, status_mhs=status_mhs, organisasi_mhs=organisasi_mhs,
                        jml_tanggungan=jml_tanggungan, jml_pendapatan=jml_pendapatan,
                        bantuan=bantuan)
        db.session.add(save)
        db.session.commit()
        return redirect(url_for('ukt.indexUkt'))


@ukt.route('/ukt-testing')
def testUkt():
    if request.method == 'GET':
        user = RelasiUser(User)
        fakultas = RelasiFakultas(Fakultas)
        jurusan = RelasiJurusan(Jurusan)
        semester = RelasiSms(Semester)
        return render_template('ukt-test-page.html', user=user, fakultas=fakultas,
                               jurusan=jurusan, semester=semester)


@ukt.route('/jurusan/<id>')
def arrayJurusan(id):
    # array = Jurusan.query.join(Fakultas).all()
    array = db.session.query(Jurusan, Fakultas).join(
        Fakultas).filter_by(id=id).all()

    data = []
    for i, x in array:
        obj = {}
        obj['id'] = i.id
        obj['jurusan'] = i.jurusan
        obj['id_fakultas'] = x.fakultas
        data.append(obj)

    # jurusan = RelasiJurusan(Jurusan)

    return jsonify({'fakultas_id': data})

app/templates/pages/ukt/ukt-add.html
{% extends 'base.html' %}
<!--- set filename -->
{% set filename='addUkt' %}
<!--- page title -->
{% block title %} Tambah Training UKT {% endblock %}
<!--- item breadcrumb -->
{% block breadcrumb %} Tamah Data {% endblock %}
<!--- content -->
{% block content %}
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Tamabah Data UKT</h4>
      </div>
      <div class="card-body">
        <form action="" method="post">
          <div class="form-group row">
            <label class="col-form-label col-md-2">Nama</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="nama">
                <option>.:: Select Name ::.</option>
                {% for x in user %}
                <option value="{{ x.id}}">{{ x.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Fakultas</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="fakultas" id="fakultas">
                <option>.:: Select Fakultas ::.</option>
                {% for x in fakultas %}
                <option value="{{ x.id}}">{{ x.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Jurusan</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="jurusan" id="list-jurusan">
                <option>.:: Select Jurusan ::.</option>
                {% for x in jurusan %}
                <option value="{{ x.id}}">{{ x.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Semester</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="semester">
                <option>.:: Select Semester ::.</option>
                {% for x in semester %}
                <option value="{{ x.id}}">{{ x.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">IPK</label>
            <div class="col-md-10">
              <input type="text" class="form-control" name="ipk" placeholder="IPK 2.8 - 4.0" />
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">Status Mhs</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="status">
                <option>.:: Select Status Mahasiswa::.</option>
                <option value="aktif">Aktif</option>
                <option value="cuti">Cuti</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">Organisasi</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="organisasi">
                <option>.:: Select Status Organiasai ::.</option>
                <option value="ada">Ada</option>
                <option value="pasif">Pasif</option>
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Jumlah Tanggungan</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="tanggungan">
                <option>.:: Select JML Tanggungan Orang Tua ::.</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">.:: Pendapatan Orang Tua ::.</label>
            <div class="col-md-10">
              <input type="text" class="form-control" name="pendapatan" />
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">Bantuan</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="bantuan">
                <option>.:: Select Bantuan ::.</option>
                <option value="terima">Terima</option>
                <option value="tidak terima">Tidak Terima</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2"></label>
            <div class="col-md-10 text-start">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
<!-- Blok JS-->
{% block js %}

<script>
  select_fakultas = document.getElementById("#fakultas");

  alert(select_fakultas.value);
</script>

<script type="text/javascript">
  function getJurusan() {
    var str = "";
    var val = document.getElementById("fakultas");
    for (i = 0; i < val.length; i++) {
      if (val[i].selected) {
        str += val[i].value + ",";
      }
    }
    var str = str.slice(0, str.length - 1);
    $.ajax({
      type: "GET",
      url: "/jurusan",
      data: "id_fakultas=" + str,
      success: function (data) {
        $("#jurusan").html(data);
      },
    });
  }
</script>
{% endblock %}

app/templates/pages/ukt/ukt-page.html
{% extends "base.html" %}
<!--- set filename -->
{% set filename='indexUkt' %}
<!--- page title -->
{% block title %} Data Training UKT {% endblock %}
<!--- item breadcrumb -->
{% block breadcrumb %} UKT {% endblock %}
<!--- content -->
{% block content %}

<div class="row">
  <div class="col-md-12 d-flex">
    <div class="card card-table flex-fill">
      <div class="card-header">
        <a href=" {{url_for('ukt.addUkt')}} " class="btn btn-primary">.:: Tambah Data ::.</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-hover table-center mb-0">
            <thead>
              <tr>
                <th>Nama</th>
                <th>Fakultas</th>
                <th>Jurusan</th>
                <th>Semester</th>
                <th>IPK</th>
                <th>Status MHS</th>
                <th>organisasi</th>
                <th>Tanggungan</th>
                <th>Pendapatan</th>
                <th>Bantuan</th>
                {#
                <th class="text-end">Action</th>
                #}
              </tr>
            </thead>
            <tbody>
              {% for _, user, fak, jur, sms in query %}
              <tr>
                <td>{{ user.nama }}</td>
                <td>{{ fak.fakultas }}</td>
                <td>{{ jur.jurusan }}</td>
                <td>{{ sms.id }}</td>
                <td>{{ _.ipk}}</td>
                <td>{{ _.status_mhs}}</td>
                <td>{{ _.organisasi_mhs}}</td>
                <td>{{ _.jml_tanggungan}}</td>
                <td>{{ _.jml_pendapatan | idr}}</td>
                <td>{{ _.bantuan | capitalize }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 d-flex">
    <div class="card card-table flex-fill">
      <div class="card-header">
        :: DATA COUNT ::
      </div>
      <div class="card-body">
        <div class="row row-sm aligns-item-start">
        <h6 class="card-title">Data Total Training = {{pcTotal}}</h6>
        <h6 class="card-title">Data Total P|Terima = {{pc1}}</h6>
        <h6 class="card-title">Data Total P|TIdak = {{pc0}}</h6>
        {# <h6 class="card-title">Data Total P|Fakultas Teknik "Terima" = {{pf1['terima']}}</h6>
        <h6 class="card-title">Data Total P|Fakultas Teknik "Teidak" = {{pf1['tidak'] | angka}}</h6> #}
       
        {# <h6 class="card-title">Data Total P|Juruan T. Informatika "Terima" = {{pj['terima']}}</h6>
        <h6 class="card-title">Data Total P|Juruan T. Informatika "Teidak" = {{pj['tidak'] | angka}}</h6> #}

        </div>
      </div>
    </div>
  </div>
</div>

    {% endblock %}
  </div>
</div>

app/templates/pages/ukt/ukt-test-page.html
{% extends 'base.html' %}
<!--- set filename -->
{% set filename='testUkt' %}
<!--- page title -->
{% block title %} Testing Data UKT {% endblock %}
<!--- item breadcrumb -->
{% block breadcrumb %} test {% endblock %}
<!--- content -->
{% block content %}
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">UJI DATA</h4>
      </div>
      <div class="card-body">
        <form action="" method="post">
          <div class="form-group row">
            <label class="col-form-label col-md-2">Nama</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="nama">
                <option>.:: Select Name ::.</option>
                {% for x in user %}
                <option value="{{ x.id}}">{{ x.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Fakultas</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="fakultas">
                <option>.:: Select Fakultas ::.</option>
                {% for x in fakultas %}
                <option value="{{ x.id}}">{{ x.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Jurusan</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="jurusan">
                <option>.:: Select Jurusan ::.</option>
                {% for x in jurusan %}
                <option value="{{ x.id}}">{{ x.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Semester</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="semester">
                <option>.:: Select Semester ::.</option>
                {% for x in semester %}
                <option value="{{ x.id}}">{{ x.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">IPK</label>
            <div class="col-md-10">
              <input type="text" class="form-control" name="ipk" placeholder="IPK 2.8 - 4.0" />
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">Status Mhs</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="status">
                <option>.:: Select Status Mahasiswa::.</option>
                <option value="aktif">Aktif</option>
                <option value="cuti">Cuti</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">Organisasi</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="organisasi">
                <option>.:: Select Status Organiasai ::.</option>
                <option value="ada">Ada</option>
                <option value="pasif">Pasif</option>
              </select>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Jumlah Tanggungan</label>
            <div class="col-md-10">
              <select class="form-control form-select" name="tanggungan">
                <option>.:: Select JML Tanggungan Orang Tua ::.</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">.:: Pendapatan Orang Tua ::.</label>
            <div class="col-md-10">
              <input type="text" class="form-control" name="pendapatan" />
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2"></label>
            <div class="col-md-10 text-start">
              <button type="submit" class="btn btn-primary">Test Data</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}