app/controllers/c_user.py
import datetime
from flask import Blueprint, redirect, render_template, request, url_for
from app.models.user_model import UserModel
from app.extensions import db

users = Blueprint('users', __name__, template_folder='../templates/pages/user')


@users.route('/users')
def indexUser():
    # x = add_months(datetime.datetime(*[int(item) for item in x.split('-')]), 1).strftime("%Y-%m-%d")

    obj_date = "2022-02-12"
    format = "%Y-%m-%d"
    toDate = datetime.datetime.strptime(obj_date, format)
    print(toDate)
    print(type(toDate))
    query = UserModel.query.all()
    for i in query:
        print(type(i.created_at))

    return render_template('user-page.html', query=query)


@users.route('/add-user', methods=['GET', 'POST'])
def addUser():
    if request.method == 'POST':
        nim = request.form.get('nim')
        nama = request.form.get('nama')
        tgl_lahir = request.form.get('tgl')
        alamat = request.form.get('alamat')
        jk = request.form.get('jenis_kelamin')
        password = request.form.get('password')

        save = UserModel(nim=nim, nama=nama, tgl_lahir=tgl_lahir,
                         alamat=alamat, jenis_kelamin=jk)
        save.setPassword(password)
        db.session.add(save)
        db.session.commit()
        return redirect(url_for('users.indexUser'))
    else:
        return render_template('add-user-page.html')

app/templates/pages/user/add-user-page.html
{% extends 'base.html' %}
<!--- set filename -->
{% set filename='addUser' %}
<!--- page title -->
{% block title %} Tambah User {% endblock %}
<!--- item breadcrumb -->
{% block breadcrumb %} Tambah Data {% endblock %}
<!--- content -->
{% block content %}
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Tambah Data User</h4>
      </div>
      <div class="card-body">
        <form action="" method="post">
          <div class="form-group row">
            <label class="col-form-label col-md-2">NIM</label>
            <div class="col-md-10">
              <input type="text" name="nim" class="form-control" />
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Nama</label>
            <div class="col-md-10">
              <input type="text" name="nama" class="form-control" />
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Tgl Lahir</label>
            <div class="col-md-10">
              <input type="date" name="tgl" class="form-control" />
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Alamat</label>
            <div class="col-md-10">
              <input type="text" name="alamat" class="form-control" />
            </div>
          </div>
          <div class="form-group row">
            <label class="col-form-label col-md-2">Jenis Kelamin</label>
            <div class="col-lg-9">
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="jenis_kelamin" id="gender_male" value="laki-laki" checked />
                <label class="form-check-label" for="gender_male"> Laki-Laki </label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="jenis_kelamin" id="gender_female" value="perempuan" />
                <label class="form-check-label" for="gender_female"> Female </label>
              </div>
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2">Password</label>
            <div class="col-md-10">
              <input type="password" name="password" class="form-control" />
            </div>
          </div>

          <div class="form-group row">
            <label class="col-form-label col-md-2"></label>
            <div class="col-md-10 text-start">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/pages/user/user-page.html
{% extends "base.html" %}
<!--- set filename -->
{% set filename='indexUser' %}
<!--- page title -->
{% block title %} Data User {% endblock %}
<!--- item breadcrumb -->
{% block breadcrumb %} User {% endblock %}
<!--- content -->
{% block content %}

<div class="row">
  <div class="col-md-12 d-flex">
    <div class="card card-table flex-fill">
      <div class="card-header">
        <a href=" {{url_for('users.addUser')}} " class="btn btn-primary">.:: Tambah Data ::.</a>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-hover table-center mb-0">
            <thead>
              <tr>
                <th>NIM</th>
                <th>Name</th>
                <th>TGL Lahir</th>
                <th>Alamat</th>
                <th>Gender</th>
                <th>Created At</th>
                <th class="text-end">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for i in query %}
              <tr>
                <td>{{i.nim}}</td>
                <td>{{i.nama}}</td>
                <td>{{(i.tgl_lahir | dateFormat) | timeIndo}}</td>
                <td>{{i.alamat}}</td>
                <td>{{i.jenis_kelamin | capitalize}}</td>
                <td>{{i.created_at | timeIndo}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}